### PR TITLE
automate running tests before committing

### LINKED ISSUE #96: As a developer I need to automate some tests to check my work before pushing
## Expected Behavior
When merging in from branches one naturally assumes that since tests on the branch are passing and tests on the parent are passing that all is well. However, sometimes we will face issues with merge conflicts and some code may be broken when these are fixed. When this happens it is easy to forget to run the test suite before pushing. 

We can aid this by setting up [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to run our tests automatically triggered by events

## Actual Behavior
At the moment this is not covered for in the application

## Acceptance Criteria
When a developer triggers a push to source control our hooks should run the test suite before pushing

## Specifications

  - Version: 0.0.03-rcwishlist

### PR DESCRIPTION
**Pull request by zacck-zz**
Fixes #96

## Proposed Changes
  - Add documentation on how to use hooks 
  -  Add git hook to hooks folder
  -

### CODE REVIEW

**Comment by r-coh** [comment]
Looks good!

**Review by r-coh — APPROVED** [review]

**Comment by zacck-zz** [comment]
@br4inii  do you see how you will start using this git hooks? Is it clear what git hooks are and how they are used?

**Comment by WanjikuMac** [comment]
@zacck this will help a lot, good.

**Review by WanjikuMac — COMMENTED** [review]
@zacck this will help a lot, good.

**Comment by zacck-zz** [comment]
@br4inii  @WanjikuMac  thank you so much for the reviews

**Comment by zacck-zz** [comment]
@br4inii  @WanjikuMac  please look at the instructions outlined in the setup docs in this PR and run them to get the changes effective let me know if you have any issues with this

**Pull request merged**
